### PR TITLE
home-page changes

### PR DESCRIPTION
**Pull request by gpanag**

### CODE REVIEW

**Comment by ptsagkis** [comment]
George is this merge the same as the one up and running at geochoros domain url???
The commit + merge seems fine to me and the code includes all latest changes but I think there is something missing from the production.

**Comment by gpanag** [comment]
It should be. Maybe something is cached from the previous version? What's missing?

**Comment by ptsagkis** [comment]
Start form here --> http://geochoros.survey.ntua.gr/walkandthecitycenter/home
If pressing map link you are redirected to the map component. 
The page looks fine. However there is a small gap on the right hand side.-->
εικόνα
This was supposed to be solved by adding this line of code `this_.map.updateSize();` line 103 at map.compononet.ts

**Comment by ptsagkis** [comment]
@gpanag  I have updated production with your latest merge and seems to work as expected. Your probably updated production before merging.

**Comment by gpanag** [comment]
Awesome!

**Pull request merged**
